### ISSUE TITLE
after the latest updates it shows this on one device

### ISSUE THREAD

**Issue by 1HyperZ** [prasad-edlabadka/homebridge-tuya-ir#65]
[14/07/2022, 22:36:17] [TuyaIR] Failed to change device status due to error raw_key can not be null
its supposed to be controlling the tv

**Comment by hashmaker1982** [comment]
version 0.2.1 come back to that version of plugin

**Comment by 1HyperZ** [comment]
> version 0.2.1 come back to that version of plugin

Now everything stop working and it doesn't even show the error in the log

**Comment by prasad-edlabadka** [comment]
Can you send some logs? There hasn't changed anything for DIY devices.

**Comment by hashmaker1982** [comment]
for me come back to that version of plugin resolve my problem , btw, check in the tuya iot project if there are all your remotes , if not just delete from tuya app and re associate.

**Comment by 1HyperZ** [comment]
> Can you send some logs? There hasn't changed anything for DIY devices.

What exactly should I send?

**Comment by Chrisrokc** [comment]
Same error here. I am only seeing the following in the Homebridge Logs. Is there a debug mode to show additional logs?

[16/07/2022, 15:56:15] [TuyaIR] Failed to change device status due to error raw_key can not be null

**Comment by Magna66** [comment]
same error here for the DIY devices, and same log one line only
Failed to change device status due to error raw_key can not be null

**Comment by prasad-edlabadka** [comment]
DIY fixed in v1.0.5. Please check and let me know

**Comment by Magna66** [comment]
Nope not fixed.
[7/23/2022, 6:33:22 PM] [TuyaIR] Failed to change device status due to error raw_key can not be null
same error returning to version 0.2.1

**Comment by prasad-edlabadka** [comment]
Which device are you trying to use? DIY for AC is not supported.

**Comment by Magna66** [comment]
> Which device are you trying to use? DIY for AC is not supported.

Not AC, it is a humidifier, just an on/off with version 0.2.1, in fact AC carrier and sanyo fan working fine with the new version 1.0.5 or 1.0.4, it is only the humidifier works with version 0.2.1, other version it shows Failed to change device status due to error raw_key can not be null

**Comment by prasad-edlabadka** [comment]
Humidifier is not tested with the plug-in. If it's a DIY device please set DIY flag to true. This will retrieve the IR code for humidifier.

**Comment by Magna66** [comment]
> Humidifier is not tested with the plug-in. If it's a DIY device please set DIY flag to true. This will retrieve the IR code for humidifier.

Tried that, did not work. Anyway version 0.2.1 is the best, working fine with everything. Will stick to that version. Thanks and best regards.

**Comment by prasad-edlabadka** [comment]
Fixed in v1.0.6. Please test and let me know.

**Comment by Magna66** [comment]
Thank you so much, yes it is fixed. All devices working fine.
