### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jeromeanthony** [prasad-edlabadka/homebridge-tuya-ir#7]
Hi Prasad,

Excited to see this package for Homebridge. 

I seem to be getting an error when I am trying to configure my device.
Going through some settings, it seems to be related to the device location being "Europe". 
I get a timeout error instead if I set it to China? 

(To confirm, my devices are Europe).

[17/07/2021, 18:29:39] TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:61:33
    at Request._callback (/usr/local/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:180:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)

Would really appreciate your assistance if possible :) 

Thanks!

**Comment by prasad-edlabadka** [comment]
This was fixed in 0.0.8. Can you please update and give it go?

**Comment by madtempest** [comment]
I am running 0.0.8 and I still get this error:

/usr/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:180
            cb(body, error);
            ^
TypeError: Cannot read property 'length' of undefined
    at /usr/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:61:33
    at Request._callback (/usr/lib/node_modules/homebridge-tuya-ir/src/lib/TuyaAPIHelper.ts:180:13)
    at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:185:22)
    at Request.emit (events.js:375:28)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:375:28)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-ir/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:481:28)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)

I have configured only an Air Conditioner Object on the IR blaster.

Thanks for the plugin - hope we can get it working.

**Comment by prasad-edlabadka** [comment]
There isn’t .length at the line mentioned. So, something is wrong with the version. Can you please try removing and reinstalling the plugin?

**Comment by madtempest** [comment]
Hi,

I uninstalled using the UI-X. Reinstalled using sudo npm install -g homebridge-tuya-ir.

Still the same problem.

I then started removing objects and have confirmed that if I configure the plugin but do not add the sub-devices to "Device Ids of devices added for IR blaster to control" which is what I assume I should be adding, then it works.

My sub-devices have a string/device ID that is 22 characters when connected to the Europe cloud.

**Comment by MoonJuhan** [comment]
The same error occurred to me, so I checked the code.

/dist/lib/TuyaApiHelper.js

```
...
fetchDevices(deviceId, cb) {
        this._apiCall(this.apiHost + `/v1.0/infrareds/${deviceId}/remotes`, "GET", {}, (_body, err) => {
            if (err) {
                this.log.error("Failed to get remotes device: " + deviceId);
                cb([]);
            }
            else {
                var body = JSON.parse(_body);
                var devs = [];
                if (body.result.length == 0) {                // length error line
...
```

It was an error on line 54 of this file.
I checked the body with the console log and found the following output.

```
{
  code: 28841101,
  msg: 'No permissions. This API is not subscribed.',
  success: false,
  t: 1626870269219
}
```

I guess it's a Tuya API authority issue.

**Comment by MoonJuhan** [comment]
I was able to solve this problem on the Tuya IoT platform.

I found and subscribed to IR Control Hub Open Service. Subscription was free, and this service authorized my project. 

My controller is not air conditioner, so it is not supported normally, but the plugin works normally. 

It would be nice if the contents were in README. I will leave Pull Request after modifying it.

<img width="1421" alt="스크린샷 2021-07-21 오후 9 31 15" src="https://user-images.githubusercontent.com/35164907/126489351-4cf0453c-2436-4e4e-9f6c-8257a2427038.png">

**Comment by madtempest** [comment]
> I found and subscribed to IR Control Hub Open Service. Subscription was free, and this service authorized my project.

This resolved my issue.

But is also seems that if you have an IR remote with more than an AC on it, the plugin will fail to render the AC at all.

Thanks for helping resolve the issue.

**Comment by prasad-edlabadka** [comment]
> > I found and subscribed to IR Control Hub Open Service. Subscription was free, and this service authorized my project.
> 
> This resolved my issue.
> 
> But is also seems that if you have an IR remote with more than an AC on it, the plugin will fail to render the AC at all.
> 
> Thanks for helping resolve the issue.

The new release should fix this. There was bug that I fixed.
